// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDIdhM8UbV8mPicfJc_mlhIvMaaKWrK20',
    appId: '1:529575409926:web:259d18d08dc84b68e80687',
    messagingSenderId: '529575409926',
    projectId: 'architecture-997ef',
    authDomain: 'architecture-997ef.firebaseapp.com',
    storageBucket: 'architecture-997ef.appspot.com',
    measurementId: 'G-VFGELXL3VE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH-U8XGjpEQXZVDnvJmlUTfxn-Q5Ymsgw',
    appId: '1:529575409926:android:6bda4c4d8eb79d7de80687',
    messagingSenderId: '529575409926',
    projectId: 'architecture-997ef',
    storageBucket: 'architecture-997ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt5lRhALjkFIrZh97yH0EoGm9m_qJdrOc',
    appId: '1:529575409926:ios:58c21c136898ee38e80687',
    messagingSenderId: '529575409926',
    projectId: 'architecture-997ef',
    storageBucket: 'architecture-997ef.appspot.com',
    iosBundleId: 'com.aykac.architecture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt5lRhALjkFIrZh97yH0EoGm9m_qJdrOc',
    appId: '1:529575409926:ios:6f2e0899098948a7e80687',
    messagingSenderId: '529575409926',
    projectId: 'architecture-997ef',
    storageBucket: 'architecture-997ef.appspot.com',
    iosBundleId: 'com.aykac.architecture.RunnerTests',
  );
}
